variables:
    CI_BUILD_REF_NAME: master
stages:
    - build
job1:
    # 是否开启 debug 模式
    # variables:
    #     CI_DEBUG_TRACE: "true"
    stage: build
    tags:
        - notes
    only:
        - master
    script:
        - git checkout master
        - git merge $CI_BUILD_REF_NAME

