stages:
    - build
job1:
    variables:
    stage: build
    tags:
        - notes
    only:
        - master
    script:
        - git checkout master
        - git merge $CI_BUILD_REF_NAME
        - echo $CI_COMMIT_MESSAGE

