stages:
    - build
job1:
    variables:
        CI_BUILD_REF_NAME: master
    stage: build
    tags:
        - notes
    only:
        - master
    script:
        - git checkout master
        - git merge $CI_BUILD_REF_NAME

